# Generated by Django 3.0 on 2023-10-06 13:05

from django.contrib.auth import get_user_model
from django.db import migrations


def transfer_profiles_data(apps, schema_editor):
    OldProfile = apps.get_model("oc_lettings_site", "Profile")
    NewProfile = apps.get_model("profiles", "Profile")
    User = apps.get_model("auth", "User")

    for old_profile in OldProfile.objects.all():
        NewProfile.objects.create(
            user=User.objects.get(id=old_profile.user.id),
            favorite_city=old_profile.favorite_city,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(transfer_profiles_data),
    ]
